
apiVersion: v1
kind: Pod
metadata:
  name: sample-workload-identity-key-vault
  namespace: default
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: workload-sa
  containers:
    - image: conrepo.azurecr.io/img2:latest
      name: myimage
      env:
      - name: KEYVAULT_URL
        value:  https://treasury.vault.azure.ne
      - name: SECRET_NAME
        value: AZP-POOL
      - name: SECRET_NAME
        value: AZP-TOKEN
      - name: SECRET_NAME
        value: AZP-URL
      - name: SECRET_NAME
        value: AZP-WORK
      - name: SECRET_NAME
        value: ClientID
      - name: SECRET_NAME
        value: TenantID

  nodeSelector:
    kubernetes.io/os: linux
