
apiVersion: v1
kind: Pod
metadata:
  name: sample-workload-identity-key-vault
  namespace: default
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: workload-sa
  containers:
    - image: conrepo.azurecr.io/img2:latest
      name: myimage
      env:
      - name: KEYVAULT_URL
        value:  https://treasury.vault.azure.net
      
  nodeSelector:
    kubernetes.io/os: linux
