apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-deployment
  labels:
    app: azdevops-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      containers:
      - name: azdevops-agent
        image: conrepo.azurecr.io/azp-agent:latest
        env:
          - name: TenantID
            valueFrom:
              secretKeyRef:
                name: azp-secrets
                key: TenantID
          - name: ClientID
            valueFrom:
              secretKeyRef:
                name: azp-secrets
                key: ClientID
          - name: AZP-URL
            valueFrom:
              secretKeyRef:
                name: azp-secrets
                key: AZP-URL
          - name: AZP-TOKEN
            valueFrom:
              secretKeyRef:
                name: azp-secrets
                key: AZP-TOKEN
          - name: AZP-POOL
            valueFrom:
              secretKeyRef:
                name: azp-secrets
                key: AZP-POOL
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-volume
      volumes:
        - name: docker-volume
          hostPath:
            path: /var/run/docker.sock
