apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: securesec
  namespace: default
spec:
  provider: azure
  secretObjects:
    - secretName: azp-secrets
      type: Opaque
      data:
        - objectName: "AZP-URL"
          key: AZP-URL
        - objectName: "AZP-TOKEN"
          key: AZP-TOKEN
        - objectName: "AZP-POOL"
          key: AZP-POOL
        - objectName: "TenantID"
          key: TenantID
        - objectName: "ClientID"
          key: ClientID
  parameters:
    usePodIdentity: "false"   # Can be true if using managed identity for pods
    seVMManagedIdentity: "true"  # To use a VM-managed identity
    userAssignedIdentityID: "3007e93f-aa54-46a3-bbe2-e518e21db921"  # Replace with your actual client ID if needed
    keyvaultName: "Treasury"   # Replace with your Key Vault name
    objects: |
      array:
        - |
          objectName: "AZP-URL"
          objectType: secret
        - |
          objectName: "AZP-TOKEN"
          objectType: secret
        - |
          objectName: "AZP-POOL"
          objectType: secret
        - |
          objectName: "TenantID"
          objectType: secret
        - |
          objectName: "ClientID"
          objectType: secret
    tenantId: "03cf716d-2f0e-4a9f-814e-e04b5fb0d41e"  # Reference tenant ID
